In [45]:
import pandas as pd
import xgboost as xgb
import numpy as np
from sklearn import datasets, linear_model

In [50]:
X_train = pd.read_csv('X_train_prep')

In [51]:
X_test = pd.read_csv('X_test_prep')

In [70]:
X= pd.read_csv('/Users/mi0310/Desktop/JPMC/train.csv')
Y_train = X["Fare"]

In [71]:
regr = linear_model.LinearRegression()

In [72]:
regr.fit(X_train, Y_train)

# Make predictions using the testing set
y_pred = regr.predict(X_test)

In [73]:
y_pred

array([ -981.2256282 ,  1381.3860646 , 12947.34240612, ...,
        5608.24260903, 12764.41133458, 11679.88294385])

In [75]:
np.savetxt("y_pred_updated.csv", y_pred, delimiter=",")

In [6]:
xgdmat=xgb.DMatrix(X_train,Y_train)
our_params={'eta':0.1,'seed':0,'subsample':0.8,'colsample_bytree':0.8,'objective':'reg:linear','max_depth':3,'min_child_weight':1}
final_gb=xgb.train(our_params,xgdmat)
tesdmat=xgb.DMatrix(X_test)
y_pred=final_gb.predict(tesdmat)
print(y_pred)

[2986.5415 3468.0735 7804.505  ... 5286.446  7804.505  8531.245 ]

In [8]:
y_pred

array([2986.5415, 3468.0735, 7804.505 , ..., 5286.446 , 7804.505 ,
       8531.245 ], dtype=float32)

In [9]:
y = pd.DataFrame(y_pred)

In [13]:
y.to_csv('Y_test.csv')

In [14]:
y_pred

array([2986.5415, 3468.0735, 7804.505 , ..., 5286.446 , 7804.505 ,
       8531.245 ], dtype=float32)

In [18]:
np.savetxt("y_pred.csv", y_pred, delimiter=",")

In [19]:
y_pred

array([2986.5415, 3468.0735, 7804.505 , ..., 5286.446 , 7804.505 ,
       8531.245 ], dtype=float32)

In [23]:
X_train.dtypes

From                    int64
To                      int64
Flight Time             int64
Class                   int64
Age_at_Booking          int64
Booking_to_flight       int64
Booking Year            int64
Booking Month           int64
Booking Is_month_end     bool
Flight Year             int64
Flight Month            int64
Flight Dayofweek        int64
Flight Is_month_end      bool
Time Label              int64
dtype: object

In [13]:
del X_train["Unnamed: 0"]

In [15]:
del X_train["Booking Dayofweek"]

In [16]:
del X_train["Booking Is_month_start"]

In [17]:
del X_train["Flight Is_month_start"]

In [21]:
X_test = X_test.drop(["Unnamed: 0","Booking Dayofweek","Booking Is_month_start","Flight Is_month_start"],axis = 1)

In [22]:
X_test.dtypes

From                    int64
To                      int64
Flight Time             int64
Class                   int64
Age_at_Booking          int64
Booking_to_flight       int64
Booking Year            int64
Booking Month           int64
Booking Is_month_end     bool
Flight Year             int64
Flight Month            int64
Flight Dayofweek        int64
Flight Is_month_end      bool
Time Label              int64
dtype: object

In [30]:
del X_train["Flight Year"]
del X_test["Flight Year"]

In [49]:
X_test

,Unnamed: 0,Unnamed: 0.1,From,To,Flight Time,Class,Age_at_Booking,Booking_to_flight,Booking Year,Booking Month,Booking Dayofweek,Booking Is_month_end,Booking Is_month_start,Flight Year,Flight Month,Flight Dayofweek,Flight Is_month_end,Flight Is_month_start,Time Label
0,0,0,1,3,19,0,11,47,2016,2,2,False,False,2016,4,0,False,False,4
1,1,1,3,1,17,0,54,43,2016,1,0,False,False,2016,3,1,False,False,3
2,2,2,3,1,13,1,49,13,2015,12,1,False,False,2016,1,0,False,False,2
3,3,3,3,2,13,0,58,31,2016,9,0,False,False,2016,10,3,False,False,2
4,4,4,7,1,17,0,16,21,2016,9,5,False,False,2016,9,5,False,False,3
5,5,5,7,6,9,0,30,39,2016,7,0,False,False,2016,8,4,False,False,2
6,6,6,3,1,20,1,42,37,2016,11,4,False,False,2016,12,6,False,False,4
7,7,7,4,1,17,0,65,31,2015,12,3,True,False,2016,1,6,True,False,3
8,8,8,2,6,11,0,25,15,2015,12,1,False,False,2016,1,2,False,False,2
9,9,9,4,1,6,0,71,42,2016,1,3,False,False,2016,2,3,False,False,1
10,10,10,7,3,11,0,37,36,2016,3,6,False,False,2016,5,0,False,False,2
11,11,11,3,2,0,0,58,37,2016,11,2,False,False,2016,12,4,False,False,0
12,12,12,1,3,22,0,61,13,2016,1,0,False,False,2016,1,6,False,False,4
13,13,13,4,2,5,0,75,3,2016,10,4,False,False,2016,10,0,False,False,1
14,14,14,6,3,13,0,52,18,2016,6,1,False,False,2016,7,5,False,False,2
15,15,15,1,3,22,0,64,2,2016,5,3,False,False,2016,5,5,False,False,4
16,16,16,3,4,18,0,49,21,2015,12,5,False,False,2016,1,5,False,False,3
17,17,17,7,3,12,0,42,36,2016,7,2,False,False,2016,8,3,False,False,2
18,18,18,5,2,10,0,44,32,2016,1,4,False,True,2016,2,1,False,False,2
19,19,19,5,4,14,1,27,4,2016,5,0,False,False,2016,5,4,False,False,3
20,20,20,1,6,20,0,13,36,2016,10,1,False,False,2016,11,2,False,False,4
21,21,21,2,6,3,0,62,26,2016,10,1,False,False,2016,10,6,False,False,0
22,22,22,7,3,17,0,21,7,2016,4,5,False,False,2016,4,5,False,False,3
23,23,23,4,1,7,0,30,34,2016,10,6,False,False,2016,11,5,False,False,1
24,24,24,7,1,16,0,43,14,2016,6,4,False,False,2016,6,4,False,False,3
25,25,25,5,7,6,0,19,30,2016,6,1,False,False,2016,7,3,False,False,1
26,26,26,2,4,12,0,53,19,2016,3,5,False,False,2016,4,3,False,False,2
27,27,27,3,5,16,0,27,29,2016,8,6,False,False,2016,9,0,False,False,3
28,28,28,2,7,8,1,42,34,2016,9,4,False,False,2016,10,3,False,False,1
29,29,29,3,7,18,0,54,16,2016,1,6,False,False,2016,1,1,False,False,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2470,2470,2470,3,2,2,0,45,4,2016,10,4,False,False,2016,10,1,False,False,0
2471,2471,2471,3,4,23,0,34,42,2016,5,1,False,False,2016,6,1,False,False,4
2472,2472,2472,3,4,19,0,55,53,2016,9,6,False,False,2016,11,3,False,False,4
2473,2473,2473,2,5,16,0,41,39,2016,10,1,False,False,2016,11,5,False,False,3
2474,2474,2474,7,2,11,0,16,56,2016,1,5,False,False,2016,2,5,False,False,2
2475,2475,2475,2,7,14,0,36,28,2016,4,2,False,False,2016,5,2,False,False,3
2476,2476,2476,1,3,19,0,26,22,2016,7,2,False,False,2016,8,3,False,False,4
2477,2477,2477,3,2,20,1,64,26,2015,12,4,False,False,2016,1,2,False,False,4
2478,2478,2478,2,3,15,0,44,21,2016,9,5,False,False,2016,9,5,False,False,3
2479,2479,2479,4,2,5,0,37,49,2016,2,3,False,False,2016,3,3,False,False,1
2480,2480,2480,3,2,15,0,45,35,2016,8,6,False,False,2016,9,6,False,False,3
2481,2481,2481,5,1,6,0,67,18,2016,9,6,False,False,2016,9,3,False,False,1
2482,2482,2482,6,7,11,0,47,21,2016,5,3,False,False,2016,5,3,False,False,2
2483,2483,2483,4,3,10,1,67,1,2016,5,0,False,False,2016,5,1,False,False,2
2484,2484,2484,1,3,22,0,16,25,2016,8,0,False,False,2016,9,4,False,False,4
2485,2485,2485,4,3,20,0,64,29,2016,8,1,False,False,2016,9,2,False,False,4
2486,2486,2486,5,6,8,1,51,37,2016,11,4,False,False,2016,12,6,False,False,1
2487,2487,2487,3,2,18,0,45,33,2016,10,3,False,False,2016,11,1,False,False,3
2488,2488,2488,6,3,13,0,56,15,2016,3,0,False,False,2016,4,1,False,False,2
2489,2489,2489,6,5,7,0,54,9,2016,6,3,False,False,2016,6,5,False,False,1
2490,2490,2490,2,1,8,0,56,30,2015,12,3,True,False,2016,1,5,False,False,1
2491,2491,2491,7,3,18,1,71,14,2016,1,2,False,False,2016,2,2,False,False,3
2492,2492,2492,4,1,22,1,62,15,2016,3,1,False,False,2016,3,2,False,False,4
2493,2493,2493,5,2,10,0,66,32,2016,9,1,False,False,2016,10,5,False,False,2
2494,2494,2494,7,1,16,0,27,36,2016,3,5,False,False,2016,5,6,False,True,3
2495,2495,2495,7,2,11,0,60,8,2016,5,6,False,False,2016,5,0,False,False,2
2496,2496,2496,3,2,20,1,37,11,2016,6,2,False,False,2016,7,6,False,False,4
2497,2497,2497,1,7,16,0,12,43,2016,5,5,False,False,2016,7,6,False,False,3
2498,2498,2498,3,1,2,1,55,14,2015,12,0,False,False,2016,1,0,False,False,0
2499,2499,2499,2,7,16,0,59,3,2016,9,3,False,False,2016,10,6,False,False,3

In [53]:
del X_train["Unnamed: 0"]
del X_test["Unnamed: 0"]

In [58]:
del X_test["Unnamed: 0.1"]

In [62]:
X_test.dtypes

From                      int64
To                        int64
Flight Time               int64
Class                     int64
Age_at_Booking            int64
Booking_to_flight         int64
Booking Year              int64
Booking Month             int64
Booking Dayofweek         int64
Booking Is_month_end       bool
Booking Is_month_start     bool
Flight Year               int64
Flight Month              int64
Flight Dayofweek          int64
Flight Is_month_end        bool
Flight Is_month_start      bool
Time Label                int64
dtype: object

In [63]:
del X_train["Flight Time"]
del X_test["Flight Time"]
del X_train["Booking Dayofweek"]
del X_test["Booking Dayofweek"]

In [68]:
X_test.dtypes

From                      int64
To                        int64
Class                     int64
Age_at_Booking            int64
Booking_to_flight         int64
Booking Month             int64
Booking Is_month_end       bool
Booking Is_month_start     bool
Flight Month              int64
Flight Dayofweek          int64
Flight Is_month_end        bool
Flight Is_month_start      bool
Time Label                int64
dtype: object

In [69]:
X_train.dtypes

From                      int64
To                        int64
Class                     int64
Age_at_Booking            int64
Booking_to_flight         int64
Booking Month             int64
Booking Is_month_end       bool
Booking Is_month_start     bool
Flight Month              int64
Flight Dayofweek          int64
Flight Is_month_end        bool
Flight Is_month_start      bool
Time Label                int64
dtype: object

In [67]:
del X_train["Flight Year"]
del X_test["Flight Year"]
del X_train["Booking Year"]
del X_test["Booking Year"]

In [76]:
xgdmat=xgb.DMatrix(X_train,Y_train)
our_params={'eta':0.1,'seed':0,'subsample':0.8,'colsample_bytree':0.8,'objective':'reg:linear','max_depth':3,'min_child_weight':1}
final_gb=xgb.train(our_params,xgdmat)
tesdmat=xgb.DMatrix(X_test)
y_pred=final_gb.predict(tesdmat)
print(y_pred)

[2909.0535 3609.8606 8095.077  ... 5192.6094 7596.0176 8302.021 ]

In [77]:
np.savetxt("y_pred_xgboost.csv", y_pred, delimiter=",")